package com.yfve.tools;

import com.yfve.engineeringmode.AhuFragment;
import com.yfve.engineeringmode.AhuLocationIFragment;
import com.yfve.engineeringmode.AhuPnFragment;
import com.yfve.engineeringmode.BezelFragment;
import com.yfve.engineeringmode.BtTestFragment;
import com.yfve.engineeringmode.ConfigFragment;
import com.yfve.engineeringmode.ConfigP2Fragment;
import com.yfve.engineeringmode.ConfigP3Fragment;
import com.yfve.engineeringmode.DisplayTestPatternFragment;
import com.yfve.engineeringmode.DspFragment;
import com.yfve.engineeringmode.DspPnFragment;
import com.yfve.engineeringmode.GyroscopeFragment;
import com.yfve.engineeringmode.MainFragment;
import com.yfve.engineeringmode.PhoneSignalStrengthsFragment;
import com.yfve.engineeringmode.PhotoTestFragment;
import com.yfve.engineeringmode.RadioSignalFragment;
import com.yfve.engineeringmode.RadioTunerFragment;
import com.yfve.engineeringmode.RadioTunerPhase2Fragment;
import com.yfve.engineeringmode.RgbPixelTextFragment;
import com.yfve.engineeringmode.SdmFragment;
import com.yfve.engineeringmode.SdmPnFragment;
import com.yfve.engineeringmode.SensorFragment;
import com.yfve.engineeringmode.SoftwareVersionsFragment;
import com.yfve.engineeringmode.TouchscreenFragment;
import com.yfve.engineeringmode.WifiDebugFragment;
import com.yfve.engineeringmode.WifiSettingsFragment;

/* loaded from: classes1.dex */
public class PublicDefine {
    public static boolean mSdWindowIsShow = false;
    public static String OUT_SPEAKER_STATE = "";
    public static int INNER_SPEAKER_STATE = -1;
    public static String mstrMainFragmentName = MainFragment.class.getSimpleName();
    public static String mstrBezelFragmentName = BezelFragment.class.getSimpleName();
    public static String mstrAhuFragmentName = AhuFragment.class.getSimpleName();
    public static String mstrApimPnFragmentName = AhuPnFragment.class.getSimpleName();
    public static String mstrApimLiFragmentName = AhuLocationIFragment.class.getSimpleName();
    public static String mstrTouchscreenFragmentName = TouchscreenFragment.class.getSimpleName();
    public static String mstrDisplayTestPatternFragment = DisplayTestPatternFragment.class.getSimpleName();
    public static String mstrRgbPixelTextFragment = RgbPixelTextFragment.class.getSimpleName();
    public static String mstrDspFragmentName = DspFragment.class.getSimpleName();
    public static String mstrDspPnFragmentName = DspPnFragment.class.getSimpleName();
    public static String mstrSdmFragmentName = SdmFragment.class.getSimpleName();
    public static String mstrSdmPnFragmentName = SdmPnFragment.class.getSimpleName();
    public static String mstrGyroscopeFragmentName = GyroscopeFragment.class.getSimpleName();
    public static String mstrRadioTunerFragment = RadioTunerFragment.class.getSimpleName();
    public static String mstrRadioTunerPhase2Fragment = RadioTunerPhase2Fragment.class.getSimpleName();
    public static String mstrPSSFragmentName = PhoneSignalStrengthsFragment.class.getSimpleName();
    public static String mstrSensorFragmentName = SensorFragment.class.getSimpleName();
    public static String mstrWifiDebugFragmentName = WifiDebugFragment.class.getSimpleName();
    public static String mstrBtTestFragmentName = BtTestFragment.class.getSimpleName();
    public static String mstrSoftwareVersionsFragmentName = SoftwareVersionsFragment.class.getSimpleName();
    public static String ConfigFragmentName = ConfigFragment.class.getSimpleName();
    public static String ConfigP2FragmentName = ConfigP2Fragment.class.getSimpleName();
    public static String RadioSignalFragmentName = RadioSignalFragment.class.getSimpleName();
    public static String WifiSettingsFragmentName = WifiSettingsFragment.class.getSimpleName();
    public static String PhotoTestFragmentName = PhotoTestFragment.class.getSimpleName();
    public static String ConfigP3FragmentName = ConfigP3Fragment.class.getSimpleName();
}
